osx_image: xcode8.3
language: objective-c

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - IOS="iOS"

  matrix:
    - DESTINATION="OS=9.1,name=iPad Air"
    - DESTINATION="OS=9.2,name=iPad Air 2"
    - DESTINATION="OS=10.1,name=iPad Pro (12.9-inch)"

    - DESTINATION="OS=9.0,name=iPhone 4s"
    - DESTINATION="OS=9.1,name=iPhone 5"
    - DESTINATION="OS=10.2,name=iPhone 7"
    - DESTINATION="OS=10.0,name=iPhone 7 Plus"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  - FRAMEWORK_SCHEME="SwiftyKeyboardObserver iOS";
  - EXAMPLE_SCHEME="Example iOS";

  # Build Framework
  - xcodebuild -project "SwiftyKeyboardObserver.xcodeproj" -scheme "$FRAMEWORK_SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
  - xcodebuild -project "SwiftyKeyboardObserver.xcodeproj" -scheme "$FRAMEWORK_SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;

  # Build Example
  - xcodebuild -project "Example/Example.xcodeproj" -scheme "$EXAMPLE_SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
  - xcodebuild -project "Example/Example.xcodeproj" -scheme "$EXAMPLE_SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
